//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteID { get; set; }
        public string Quote_Type { get; set; }
        public string Contact { get; set; }
        public string Task { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Task_type { get; set; }
        public Nullable<int> status { get; set; }
    }
}
